[package]
name = "spsc-rs"
version = "0.1.0"
edition = "2021"

[features]
default = ["async"]
async = ["futures"]

[dependencies]
futures = { version = "0.3", default-features = false, optional = true }

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt"] }
